model_name: "Shanna"
year: 1992
proxy: "http://90.63.185.232:30000/224c7726090deb91b663f22dc40d614f/reset?proxy=90.63.185.232:30003"
fruits:
  - cerise:
    x: 858
    y: 450
    color: f9a7c
  - pasteque:
    x: 862
    y: 616
    color: fce66
  - raisin:
    x: 1060
    y: 432
    color: 6827eb
bios:
  - "lG slhline\nCoucou moi c'est Shanna\n31 ans\nPeche a la Recherche d'une Aventure Sucree\nViens discuter je mords pas"
  - "lG slhline\nCoucou moi c'est Shanna\n31 ans\nExploratrice des Saveurs Sucrees de la Vie        \nViens discuter je mords pas"
  - "lG slhline\nCoucou moi c'est Shanna\n31 ans\nEsprit Tropical\nViens discuter je mords pas"
  - "lG slhline\nCoucou moi c'est Shanna\n31 ans\nConversations Petillantes\nViens discuter je mords pas"
cities:
- "Albertville"
- "Albi"
- "Alencon"
- "Ales"
- "Allevard"
- "Amiens"
- "Amilly"
- "Ancenis"
- "Andenne"
- "Anderlecht"
- "Andresy"
- "Angers"
- "Angouleme"
- "Annecy"
- "Annecy-le-Vieux"
- "Annonay"
- "Antibes"
- "Anvers"
- "Aoste"
- "Apprieu"
- "Arbois"
- "Argenteuil"
- "Arlanc"
- "Arles"
- "Arles sur Tech"
- "Asnieres-sur-Seine"
- "Aspet"
- "Ath"
- "Aubagne"
- "Aubenas"
- "Aubervilliers"
- "Auderville"
- "Aulnay-sous-Bois"
- "Aurillac"
- "Auterive"
- "Autun"
- "Auxerre"
- "Auxonne"
- "Auzances"
- "Auzouer en Touraine"
- "Avallon"
- "Avignon"
- "Aix les thermes"
- "Azay Le Rideau"
- "Baccarat"
- "Bannalec"
- "Banyuls sur Mer"
- "Bar Sur Aube"
- "Bar sur seine"
- "Bar-le-Duc"
- "Barc"
- "Barcelonnette"
- "Barfleur"
- "Barquet"
- "Barr"
- "Bastia"
- "Bayeux"
- "Bayonne"
- "Bazas"
- "Bazoches les Gallerardes"
- "Beaucaire"
- "Beauchamp"
- "Beaugency"
- "Beaumes-de-Venise"
- "Beaumont de Lomagne"
- "Beaumont en Auge"
- "Beaurepaire"
- "Beauvais"
- "Bellac"
- "Bellegarde Sur Valserine"
- "Belleville"
- "Belley"
- "Berck sur Mer"
- "Bergerac"
- "Bergues"
- "Bernay"
- "Besseges"
- "Bethune"
- "Beynes"
- "Beziers"
- "Binic-Etables-sur-Mer"
- "Biscarrosse"
- "Blain"
- "Blamont"
- "Blenod Les Pont a Mousson"
- "Blere"
- "Blois"
- "Boisgervilly"
- "Bollene"
- "Bondues"
- "Bonnat"
- "Bonnefoi"
- "Bonnetable"
- "Bonneville"
- "Bonnieux"
- "Bordeaux"
- "Bormes-les-Mimosas"
- "Bort les orgues"
- "Boulogne sur Mer"
- "Boulogne-Billancourt"
- "Bouloire"
- "Bourcefranc-le-Chapus"
- "Bourg en bresse"
- "Bourganeuf"
- "Bourges"
- "Bourgoin-Jallieu"
- "Bouzonville"
- "Brantome"
- "Brecey"
- "Breil sur Roya"
- "Breteuil"
- "Briancon"
- "Brignoles"
- "Brou"
- "Brouage"
- "Bruges"
- "Brunehaut"
- "Buzancais"
- "Cabanac et Villagrains"
- "Caen"
- "Cagnes-sur-Mer"
- "Cahors"
- "Calais"
- "Cambrai"
- "Campan"
- "Campigny"
- "Cancale"
- "Cannes"
- "Capbreton"
- "Caraman"
- "Carcassonne"
- "Carmaux"
- "Carpentras"
- "Carquefou"
- "Carrieres-sur-Seine"
- "Carsix"
- "Cassel"
- "Cassis"
- "Castelsarrasin"
- "Casttelnaudary"
- "Cavaillon"
- "Cergy"
- "Cessenon-sur-Orb"
- "Cesson"
- "Cestas"
- "Challes"
- "Chalon sur soane"
- "Chalons en Champagne"
- "Chalus"
- "Chambery"
- "Chamblac"
- "Chamonix-Mont-Blanc"
- "Champigny-sur-Marne"
- "Champtoce sur Loire"
- "Charenton-le-Pont"
- "Charleroi"
- "Chartres"
- "Chateau chinon"
- "Chateau Gontier"
- "Chateau thierry"
- "Chateaubriant"
- "Chateaudun"
- "Chateauneuf la Foret"
- "Chateauneuf-du-Faou"
- "Chatellerault"
- "Chatou"
- "Chaude aigues"
- "Chauffailes"
- "Chaumont"
- "Chazelles sur Lyon"
- "Chenove"
- "Cherbourg"
- "Cheux"
- "Civray"
- "Clamecy"
- "Clermont l'Herault"
- "Clichy"
- "Cluses"
- "Cognac"
- "Collioure"
- "Collonges-la-Rouge"
- "Colmar"
- "Colombes"
- "Combourg"
- "Conques"
- "Cordes-sur-Ciel"
- "Cornieville"
- "Cosne-Cours-Sur-Loire"
- "Coulommiers"
- "Courbevoie"
- "Courcemont"
- "Courgains"
- "Courtrai"
- "Coutras"
- "Couville"
- "Couvin"
- "Creil"
- "Crest"
- "Creteil"
- "Crulai"
- "Cubnezais"
- "Cugand"
- "Culoz"
- "Culoz-Beon"
- "Dax"
- "Deauvilles"
- "Die"
- "Dieppe"
- "Diest"
- "Dieuze"
- "Digne les bains"
- "Digoin"
- "Dijon"
- "Dinant"
- "Dives sur Mer"
- "Divonne les bains"
- "Dole"
- "Domessin"
- "Douai"
- "Doullens"
- "Dourgne"
- "Draguignan"
- "Drancy"
- "Dreux"
- "Durtal"
- "Ecorpain"
- "Egueon chantome"